server:
  port: 80

spring:
  #注册到zookeeper中的服务名
  application:
    name: cloud-consumer-order
  #consul地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}