server:
  port: 8803


eureka:
  client:
    #表示是否将自己注册进eureka server 默认true
    register-with-eureka: true
    #是否从eureka server 中抓取已有的注册信息，默认为true。 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: receive-8803 #在信息列表显示的主机名称
    prefer-ip-address: true #访问的路径变为ip地址

spring:
  application:
    name: cloud-stream-consumer8803
  cloud:
    stream:
      binders: #此处配置要绑定的rabbitmq服务信息
        defaultRabbit: #表示定义的名称，用于binding的整合
          type: rabbit #消息组件类型
          environment: #rabbitmq环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #通道名称
          destination: studyExchange #exChange名称
          content-type: application/json #消息类型，本次为json，文本类型为test/plain
          default-binder: defaultRabbit #设置要绑定的消息服务
          group: Leon #分组