server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    #网关配置
    gateway:
      discovery:
        locator:
          enabled: true #开启从服务中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由id，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配服务的路由地址
          uri: lb://cloud-payment-service #通过服务名进行负载均衡动态路由
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
        - id: payment_routh2 #路由id，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配服务的路由地址
          uri: lb://cloud-payment-service #通过服务名进行负载均衡动态路由
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            ##其他断言规则####详见官网
            #After Before Between Cookie Header Host Method Path Query ReadBodyPredicateFactory RemoteAddr Weight CloudFoundryRouteService

############## Eureka ############
eureka:
  client:
    #表示是否将自己注册进eureka server 默认true
    register-with-eureka: true
    #是否从eureka server 中抓取已有的注册信息，默认为true。 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  #指定服务信息 可去除主机名称
  instance:
    instance-id: cloud-gateway-service
    #访问路径可以显示ip地址
    prefer-ip-address: true
    hostname: cloud-gateway-service
