server:
  port: 85

spring:
  application:
    name: nacos-order-comsumer
  cloud:
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard 地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始一次+1扫描，知道找到未被占用的端口
        port: 8719
        clientIp: 192.168.21.30


management:
  endpoints:
    web:
      exposure:
        #监控扫描节点全开
        include: '*'

#服务端
service-url:
  server: http://nacos-payment-provider

#激活sentinel对Feign的支持
feign:
  sentinel:
    enabled: true